---
abstract: 'client library for memcached (memory cache daemon)'
author:
  - 'Brad Fitzpatrick <brad@danga.com>'
build_requires:
  ExtUtils::MakeMaker: 0
configure_requires:
  ExtUtils::MakeMaker: 0
dynamic_config: 1
generated_by: 'ExtUtils::MakeMaker version 6.62, CPAN::Meta::Converter version 2.112621'
license: unknown
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Cache-Memcached
no_index:
  directory:
    - t
    - inc
requires:
  Encode: 0
  Storable: 0
  String::CRC32: 0
  Time::HiRes: 0
version: 1.30
